version: "3"

services:
    ai-backend:
        container_name: ai-backend
        volumes:
            - ./:/app
        build:
            context: ./
            dockerfile: Dockerfile
        image: ai
        ports:
            - "5000:5000"
        command: bash -c "python app.py "